'use strict';
const $=id=>document.getElementById(id);
const NAV=[['dashboard','◈','Dashboard'],['maintenance','⚒','Bakımlar'],['issues','⚠','Arızalar'],['tools','▣','Takım Çantası'],['expenses','₺','Masraflar'],['fuel','⛽','Yakıt'],['reminders','▦','Tarihler'],['documents','▤','Belgeler']];
const PATHS={vehicle:'data/vehicle.json',maintenance:'data/maintenance.json',plans:'data/service-plans.json',issues:'data/issues.json',expenses:'data/expenses.json',fuel:'data/fuel.json',reminders:'data/reminders.json',tools:'inventory.json'};
const initialVehicle={schemaVersion:1,vehicle:{make:'Mazda',model:'MX-3',year:1994,engine:'K8 1.8 V6',transmission:'Manual'},odometer:{currentKm:null,updatedAt:null,history:[]}};
const empty=k=>k==='vehicle'?structuredClone(initialVehicle):k==='tools'?{app:'mx3-tools',version:1,checked:[]}: {schemaVersion:1,records:[]};
const state={page:'dashboard',data:{},shas:{},connected:false,busy:new Set(),errors:{},filter:'',search:'',toolOpen:new Map(),toolChanges:new Map(),toolBusy:false,editing:null,selectedType:null,pending:new Map()};
const hostname=location.hostname,segments=location.pathname.split('/').filter(Boolean);
const github={owner:GITHUB_OWNER||(hostname.endsWith('.github.io')?hostname.split('.')[0]:''),repo:GITHUB_REPO||(hostname.endsWith('.github.io')?segments[0]:''),token:GITHUB_TOKEN};
const own=Object.hasOwn(globalThis,'OWNED')?OWNED:[];
const tools=DATA.flatMap((g,i)=>g.items.map(item=>({id:`p${i+1}-${item[0]}`,name:item[1],desc:item[2],group:i})));
const categoryNames={mechanical:'Mekanik',engine:'Motor',drivetrain:'Aktarma',electrical:'Elektrik',suspension:'Süspansiyon',body:'Kaporta',other:'Diğer',tools:'Ekipman',parts:'Parça',service:'Servis',insurance:'Sigorta',tax:'Vergi',parking:'Otopark',accessory:'Aksesuar',fuel:'Yakıt'};
const fieldDefs={
 maintenance:[['title','İşlem adı','text',true],['date','Tarih','date',true],['km','Kilometre','number'],['category','Kategori','select:engine,mechanical,drivetrain,electrical,suspension,body,other'],['partsCost','Parça maliyeti (₺)','number'],['laborCost','İşçilik maliyeti (₺)','number'],['description','Yapılan işlemler','textarea'],['parts','Kullanılan parçalar (virgülle)','text'],['issueIds','Bağlı arıza ID’leri (virgülle)','text'],['notes','Notlar','textarea']],
 issues:[['title','Sorun başlığı','text',true],['reportedDate','Tespit tarihi','date'],['reportedKm','Kilometre','number'],['status','Durum','select:open,diagnosing,waiting,resolved,cancelled'],['severity','Önem','select:low,medium,high,critical'],['symptoms','Belirtiler','textarea'],['notes','Teşhis / notlar','textarea'],['resolvedDate','Çözüm tarihi','date']],
 expenses:[['title','Harcama adı','text',true],['date','Tarih','date',true],['amount','Tutar (₺)','number',true],['category','Kategori','select:tools,parts,service,insurance,tax,parking,accessory,other'],['notes','Not','textarea']],
 fuel:[['date','Tarih','date',true],['km','Kilometre','number',true],['liters','Litre','number',true],['totalCost','Toplam ücret (₺)','number',true],['fullTank','Depoyu tam doldurdum','checkbox'],['station','İstasyon','text'],['notes','Notlar','textarea']],
 reminders:[['title','Başlık','text',true],['type','Tür','select:inspection,trafficInsurance,casco,tax,other'],['dueDate','Son tarih','date',true],['status','Durum','select:active,completed'],['notes','Not','textarea']],
 plans:[['title','Bakım adı','text',true],['intervalKm','Tekrar aralığı (km)','number'],['intervalMonths','Tekrar aralığı (ay)','number'],['lastDate','Son bakım tarihi','date'],['lastKm','Son bakım kilometresi','number'],['notes','Notlar','textarea']]
};
const enums={status:{open:'Açık',diagnosing:'Teşhis',waiting:'Parça bekleniyor',resolved:'Çözüldü',cancelled:'İptal',active:'Aktif',completed:'Tamamlandı'},severity:{low:'Düşük',medium:'Orta',high:'Yüksek',critical:'Kritik'},type:{inspection:'Muayene',trafficInsurance:'Trafik sigortası',casco:'Kasko',tax:'MTV',other:'Diğer'}};
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const currency=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(Number(n)||0);
const dateTR=s=>s?new Date(s+'T12:00:00').toLocaleDateString('tr-TR'):'—';
const uid=prefix=>`${prefix}-${(globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2))}`;
const today=()=>new Date().toLocaleDateString('sv-SE');
const records=k=>state.data[k]?.records||[];
const bytesToBase64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s)};
const base64ToBytes=s=>Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0));
const encode=o=>bytesToBase64(new TextEncoder().encode(JSON.stringify(o,null,2)+'\n'));
const decode=c=>JSON.parse(new TextDecoder().decode(base64ToBytes(c)));
function ghUrl(path){return `https://api.github.com/repos/${encodeURIComponent(github.owner)}/${encodeURIComponent(github.repo)}/contents/${path.split('/').map(encodeURIComponent).join('/')}`}
function headers(){return {Accept:'application/vnd.github+json',Authorization:`Bearer ${github.token}`,'X-GitHub-Api-Version':'2022-11-28'}}
async function readPath(path){const r=await fetch(ghUrl(path)+'?t='+Date.now(),{headers:headers(),cache:'no-store'});if(r.status===404)return {sha:null,data:null};if(!r.ok)throw Error(`Okuma hatası (${r.status}) • ${path}`);const doc=await r.json();return {sha:doc.sha,data:doc.content?decode(doc.content):null};}
async function writePath(path,data,sha,msg,raw=false){const payload=raw?bytesToBase64(data):encode(data);const body={message:msg||`chore: update ${path}`,branch:'main',content:payload};if(sha)body.sha=sha;const r=await fetch(ghUrl(path),{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===409||r.status===422)throw Object.assign(Error('GitHub sürüm çakışması'),{conflict:true});if(!r.ok){const err=await r.json().catch(()=>({}));throw Error(`Kayıt hatası (${r.status}): ${err.message||path}`)}return (await r.json()).content.sha;}
let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600)}
function setSync(msg,error=false){$('syncStatus').textContent=msg;$('syncShort').textContent=msg;document.querySelector('.dot').style.background=error?'#f29390':msg.includes('kaydedildi')||msg.includes('Bağlı')?'#80c9a0':'#f17756'}
function clone(x){return structuredClone(x)}
function remember(k){try{localStorage.setItem('mx3-v2-'+k,JSON.stringify(state.data[k]))}catch{}}
function readLocal(k){try{return JSON.parse(localStorage.getItem('mx3-v2-'+k))}catch{return null}}
async function connect(){if(!github.token||github.token==='TOKEN_BURAYA'||!github.owner||!github.repo){setSync('config.js ayarlanmalı',true);toast('config.js içindeki token ve repo bilgilerini kontrol et');for(const k of Object.keys(PATHS))state.data[k]=readLocal(k)||empty(k);render();return}setSync('GitHub’dan okunuyor…');try{const keys=Object.keys(PATHS);const results=await Promise.all(keys.map(async k=>[k,await readPath(PATHS[k])]));for(const [k,v] of results){state.shas[k]=v.sha;state.data[k]=v.data??empty(k);if(k==='tools'&&!Array.isArray(state.data[k].checked))throw Error('inventory.json checked alanı hatalı');remember(k)}state.connected=true;setSync('GitHub bağlı ✓');render()}catch(e){state.connected=false;setSync('Bağlantı hatası',true);toast(e.message);for(const k of Object.keys(PATHS))state.data[k]??=readLocal(k)||empty(k);render()}}
// Append/change/remove one record against the latest remote version, avoiding silent overwrites.
async function mutate(k,operation){if(!state.connected)throw Error('GitHub bağlı değil; kayıt yapılmadı');if(state.busy.has(k))throw Error('Bu bölüm için başka kayıt işlemi sürüyor');state.busy.add(k);setSync('Kaydediliyor…');try{for(let attempt=0;attempt<4;attempt++){const remote=await readPath(PATHS[k]);const obj=remote.data??empty(k);const next=operation(clone(obj));try{const sha=await writePath(PATHS[k],next,remote.sha,`chore: update MX-3 ${k}`);state.data[k]=next;state.shas[k]=sha;remember(k);setSync('GitHub’a kaydedildi ✓');render();return next}catch(e){if(!e.conflict||attempt===3)throw e}}}catch(e){setSync('Kaydetme hatası',true);throw e}finally{state.busy.delete(k)}}
function saveRecord(k,entry){return mutate(k,obj=>{const list=obj.records??=[];const i=list.findIndex(r=>r.id===entry.id);if(i>=0)list[i]=entry;else list.unshift(entry);return obj})}
function delRecord(k,id){return mutate(k,obj=>{obj.records=(obj.records||[]).filter(r=>r.id!==id);return obj})}
function saveVehicle(km){return mutate('vehicle',obj=>{const before=obj.odometer.currentKm;if(before!==null&&km<before&&!confirm('Girilen km mevcut kilometreden düşük. Yine de geçmiş ölçüm olarak eklemek istiyor musun?'))throw Error('Vazgeçildi');obj.odometer.history.push({id:uid('odo'),date:today(),km,source:'manual'});if(before===null||km>=before){obj.odometer.currentKm=km;obj.odometer.updatedAt=today()}return obj})}
function nav(page){state.page=page;state.search='';render();window.scrollTo({top:0,behavior:'instant'})}
function navUI(){const html=NAV.map(([id,icon,name])=>`<button class="navitem ${state.page===id?'active':''}" data-page="${id}"><span class="ico">${icon}</span>${name}</button>`).join('');$('nav').innerHTML=html;$('mobilebar').innerHTML=[...NAV.slice(0,4),['more','☷','Diğer']].map(([id,ic,label])=>`<button class="${(state.page===id||(id==='more'&&NAV.slice(4).some(n=>n[0]===state.page)))?'active':''}" data-page="${id}"><b>${ic}</b>${label}</button>`).join('')}
function metric(label,value,hint){return `<div class="card"><small>${label}</small><div class="metric">${value}</div><div class="hint">${hint||'&nbsp;'}</div></div>`}
function totalCosts(){return records('maintenance').reduce((s,x)=>s+(+x.partsCost||0)+(+x.laborCost||0),0)+records('expenses').reduce((s,x)=>s+(+x.amount||0),0)+records('fuel').reduce((s,x)=>s+(+x.totalCost||0),0)}
function statusTag(value){const t=enums.status[value]||value||'Açık';return `<span class="chip ${['resolved','completed'].includes(value)?'good':['high','critical','open','active'].includes(value)?'warn':''}">${esc(t)}</span>`}
function dateDiff(s){if(!s)return null;const t=new Date(s+'T12:00:00'),d=new Date();d.setHours(12,0,0,0);return Math.round((t-d)/86400000)}
function planned(){return records('plans').map(p=>{let dueKm=null,dueDate=null;if(p.intervalKm&&p.lastKm!==null&&p.lastKm!==undefined&&p.lastKm!=='')dueKm=Number(p.lastKm)+Number(p.intervalKm);if(p.intervalMonths&&p.lastDate){let d=new Date(p.lastDate+'T12:00:00');d.setMonth(d.getMonth()+Number(p.intervalMonths));dueDate=d.toLocaleDateString('sv-SE')}const odo=state.data.vehicle?.odometer.currentKm;const kmLeft=dueKm!=null&&odo!=null?dueKm-odo:null;const daysLeft=dueDate?dateDiff(dueDate):null;const overdue=(kmLeft!=null&&kmLeft<=0)||(daysLeft!=null&&daysLeft<=0);return {...p,dueKm,dueDate,kmLeft,daysLeft,overdue}})}
function dashboard(){const km=state.data.vehicle?.odometer.currentKm;const openIssues=records('issues').filter(x=>!['resolved','cancelled'].includes(x.status)).length;const plans=planned();const toolcount=state.data.tools?.checked?.filter(id=>tools.some(t=>t.id===id)).length||0;const soon=records('reminders').filter(x=>x.status!=='completed').sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return `<section class="hero"><span class="caps">THE PROJECT / SINCE 1994</span><h2>MAZDA MX-3 <span style="color:var(--accent)">1.8 V6</span></h2><p>K8 DOHC 24V • Manuel • Bakım geçmişi, arızalar ve masraflar tek garajda. GitHub'da saklanan kişisel servis defterin.</p><button class="btn orange" data-action="odo">＋ Kilometre güncelle</button></section><div class="cards">${metric('GÜNCEL KİLOMETRE',km===null||km===undefined?'—':num(km)+' <em>km</em>','Son kayda göre')}${metric('AÇIK ARIZALAR',openIssues,'Takip edilen problemler')}${metric('BAKIM PLANLARI',plans.length,plans.filter(p=>p.overdue).length+' gecikmiş')}${metric('TOPLAM MASRAF',currency(totalCosts()),'Kayıtlı harcamalar')}</div><div class="sectiontitle"><h2>Hızlı işlemler</h2></div><div class="action-grid"><button class="action" data-add="maintenance"><b>⚒</b>Bakım ekle</button><button class="action" data-add="fuel"><b>⛽</b>Yakıt ekle</button><button class="action" data-add="issues"><b>⚠</b>Arıza ekle</button><button class="action" data-add="expenses"><b>₺</b>Masraf ekle</button></div><div class="columns" style="margin-top:23px"><section class="panel"><h3>Yaklaşan işler</h3>${plans.length?plans.slice(0,5).map(p=>`<div class="entry"><div><h4>${esc(p.title)}</h4><p>${p.dueKm!=null?num(p.dueKm)+' km':''} ${p.dueDate?' • '+dateTR(p.dueDate):''}</p></div>${p.overdue?'<span class="chip warn">Gecikmiş</span>':'<span class="chip">Planlı</span>'}</div>`).join(''):'<div class="empty">Henüz bakım planı yok. Bakımlar sayfasından periyodik bakım tanımlayabilirsin.</div>'}</section><section class="panel"><h3>Hatırlatıcılar</h3>${soon.length?soon.slice(0,5).map(r=>`<div class="entry"><div><h4>${esc(r.title)}</h4><p>${dateTR(r.dueDate)}</p></div>${dateDiff(r.dueDate)<0?'<span class="chip warn">Geçti</span>':`<span class="chip">${dateDiff(r.dueDate)} gün</span>`}</div>`).join(''):'<div class="empty">Muayene ve sigorta tarihlerini buraya ekleyebilirsin.</div>'}</section></div><div class="sectiontitle"><h2>Garaj durumu</h2></div><div class="panel"><div class="rows"><div class="keyval"><small>Takım envanteri</small><strong>${toolcount} / ${tools.length}</strong></div><div class="keyval"><small>Bakım kaydı</small><strong>${records('maintenance').length}</strong></div><div class="keyval"><small>Yakıt kaydı</small><strong>${records('fuel').length}</strong></div></div></div>`}
function section(k,title,desc){return `<div class="listHeader"><div><h2>${title}</h2><p class="sectionIntro">${desc}</p></div><button class="btn orange" data-add="${k}">＋ Yeni ekle</button></div>`}
function entryCard(k,r){let desc='',cost=null;switch(k){case'maintenance':desc=`${dateTR(r.date)} • ${r.km!=null?num(r.km)+' km • ':''}${esc(categoryNames[r.category]||'Bakım')}`;cost=(+r.partsCost||0)+(+r.laborCost||0);break;case'issues':desc=`${dateTR(r.reportedDate)} • ${esc(r.symptoms||r.notes||'')}`;break;case'expenses':desc=`${dateTR(r.date)} • ${esc(categoryNames[r.category]||'Diğer')}`;cost=+r.amount||0;break;case'fuel':desc=`${dateTR(r.date)} • ${num(r.km)} km • ${num(r.liters)} L • ${r.fullTank?'Tam depo':'Kısmi dolum'}`;cost=+r.totalCost||0;break;case'reminders':desc=`${dateTR(r.dueDate)} • ${esc(enums.type[r.type]||'Diğer')}`;break;case'plans':desc=`${r.intervalKm?num(r.intervalKm)+' km aralık • ':''}${r.intervalMonths?r.intervalMonths+' ay aralık':''}`;break}return `<div class="entry"><div><h4>${esc(r.title||r.station||'Yakıt dolumu')}</h4><p>${desc}</p>${r.notes?`<p>${esc(r.notes)}</p>`:''}${(r.attachments||[]).map(a=>`<button class="btn tiny" data-file="${esc(a.path)}">📎 ${esc(a.name)}</button>`).join('')}</div><div class="right">${cost!=null?`<span class="price">${currency(cost)}</span>`:''}${r.status?statusTag(r.status):''}<button class="btn tiny" data-edit="${k}:${esc(r.id)}" aria-label="Düzenle">✎</button><button class="btn tiny danger" data-delete="${k}:${esc(r.id)}" aria-label="Sil">×</button></div></div>`}
function listPage(k,title,desc){return `${section(k,title,desc)}${k==='maintenance'?`<div class="sectiontitle"><h2>Bakım planları</h2><button class="btn tiny" data-add="plans">＋ Plan ekle</button></div><div class="panel">${records('plans').length?records('plans').map(x=>entryCard('plans',x)).join(''):'<div class="empty">Bakım aralıklarını kendin belirle. Manuelden doğrulanmamış aralıklar otomatik eklenmez.</div>'}</div><div class="sectiontitle"><h2>Bakım geçmişi</h2></div>`:''}${k==='expenses'?expenseSummary():''}${k==='fuel'?fuelSummary():''}<div class="panel">${records(k).length?records(k).slice().sort((a,b)=>(b.date||b.reportedDate||b.dueDate||'').localeCompare(a.date||a.reportedDate||a.dueDate||'')).map(r=>entryCard(k,r)).join(''):'<div class="empty">Henüz kayıt yok. İlk kaydını yukarıdaki butondan ekleyebilirsin.</div>'}</div>`}
function expenseSummary(){const groups=new Map();for(const r of records('maintenance'))groups.set('Bakım',(groups.get('Bakım')||0)+(+r.partsCost||0)+(+r.laborCost||0));for(const r of records('expenses')){const k=categoryNames[r.category]||'Diğer';groups.set(k,(groups.get(k)||0)+(+r.amount||0))}for(const r of records('fuel'))groups.set('Yakıt',(groups.get('Yakıt')||0)+(+r.totalCost||0));const arr=[...groups].filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...arr.map(x=>x[1]));return `<div class="cards">${metric('TOPLAM HARCAMA',currency(totalCosts()),'Bakım + masraf + yakıt')}${metric('BAKIM GİDERLERİ',currency(records('maintenance').reduce((s,x)=>s+(+x.partsCost||0)+(+x.laborCost||0),0)),'Servis geçmişinden')}${metric('YAKIT GİDERLERİ',currency(records('fuel').reduce((s,x)=>s+(+x.totalCost||0),0)),'Dolum kayıtlarından')}${metric('BAĞIMSIZ MASRAFLAR',currency(records('expenses').reduce((s,x)=>s+(+x.amount||0),0)),'Tekrar sayılmaz')}</div><div class="panel"><h3>Kategori dağılımı</h3>${arr.length?`<div class="bars">${arr.map(([k,v])=>`<div class="barcol"><div title="${esc(k)}: ${currency(v)}" class="bar" style="height:${Math.max(2,v/max*145)}px"></div><small>${esc(k)}</small></div>`).join('')}</div><div class="legend">${arr.map(([k,v])=>`<div><span><i></i>${esc(k)}</span><strong>${currency(v)}</strong></div>`).join('')}</div>`:'<p class="empty">Grafik için harcama ekle.</p>'}</div>`}
function fuelCalculations(){const all=records('fuel').slice().sort((a,b)=>Number(a.km)-Number(b.km)||String(a.date).localeCompare(String(b.date)));const full=all.filter(r=>r.fullTank);let litres=0,km=0,segments=0;for(let i=1;i<full.length;i++){const start=all.indexOf(full[i-1]),end=all.indexOf(full[i]),d=Number(full[i].km)-Number(full[i-1].km);if(d<=0)continue;const l=all.slice(start+1,end+1).reduce((s,r)=>s+Number(r.liters||0),0);if(l>0){litres+=l;km+=d;segments++}}return {avg:km>0?litres/km*100:null,segments}}
function fuelSummary(){const f=records('fuel'),calc=fuelCalculations();const total=f.reduce((s,x)=>s+(+x.totalCost||0),0);const liters=f.reduce((s,x)=>s+(+x.liters||0),0);return `<div class="cards">${metric('ORTALAMA TÜKETİM',calc.avg===null?'—':num(calc.avg)+' <em>L/100 km</em>',calc.segments+' geçerli tam-depo aralığı')}${metric('ALINAN YAKIT',num(liters)+' <em>L</em>','Tüm dolumlar')}${metric('TOPLAM YAKIT',currency(total),'Kayıtlı dolumlar')}${metric('ORT. LİTRE FİYATI',liters?currency(total/liters):'—','Ödenen toplam / litre')}</div><p class="sectionIntro">Tüketim yalnızca ardışık tam depo kayıtları arasındaki kilometreye ve aradaki bütün dolum litrelerine göre hesaplanır.</p>`}
function toolPage(){const checked=new Set(state.data.tools?.checked||[]),completed=tools.filter(x=>checked.has(x.id)).length;const query=state.search.toLocaleLowerCase('tr'),filter=state.filter;const items=DATA.map((g,i)=>({...g,index:i,items:g.items.map(x=>({id:`p${i+1}-${x[0]}`,name:x[1],desc:x[2]})).filter(x=>(!query||(x.name+' '+x.desc).toLocaleLowerCase('tr').includes(query))&&(!filter||(filter==='owned'?checked.has(x.id):!checked.has(x.id))))})).filter(x=>x.items.length);return `<div class="cards">${metric('ALINAN',completed,'Toplam ${tools.length} parça')}${metric('ALINACAK',tools.length-completed,'Kalan ekipman')}${metric('TAMAMLANMA',Math.round(completed/tools.length*100)+'%','Alışveriş ilerlemesi')}${metric('GUNPLA SETİ','✓','Başlangıç ekipmanı')}</div><div class="panel"><h3>Zaten sende olanlar</h3><div class="pillset">${OWNED.map(t=>`<span>✓ ${esc(t)}</span>`).join('')}</div></div><div class="toolbar"><input type="search" id="toolSearch" value="${esc(state.search)}" placeholder="Alet ara..."><select id="toolFilter"><option value="">Tümü</option><option value="owned" ${filter==='owned'?'selected':''}>Aldıklarım</option><option value="needed" ${filter==='needed'?'selected':''}>Alınacaklar</option></select></div>${items.map(g=>`<details class="group" data-group="${g.index}" ${query||filter||(state.toolOpen.get(g.index)??(g.index<2))?'open':''}><summary><strong>${g.index+1}. ${esc(g.title)}</strong><small>${g.items.filter(x=>checked.has(x.id)).length}/${g.items.length} görüntülenen</small></summary>${g.items.map(x=>`<label class="toolitem ${checked.has(x.id)?'done':''}"><input type="checkbox" data-tool="${x.id}" ${checked.has(x.id)?'checked':''}><div><span>${esc(x.name)}</span><small>${esc(x.desc)}</small></div></label>`).join('')}</details>`).join('')||'<div class="empty">Eşleşme bulunamadı.</div>'}`}
function docsPage(){const found=[];for(const k of ['maintenance','issues','expenses','fuel','reminders'])for(const r of records(k))for(const a of r.attachments||[])found.push({k,r,a});return `<div class="sectiontitle"><div><h2>Fotoğraflar ve faturalar</h2><p class="sectionIntro">İlgili bakım, arıza veya masraf kaydından dosya yükleyebilirsin.</p></div></div><div class="warnbox">GitHub repository'si public ise buraya yüklediğin belgeler de herkese açıktır. Kişisel bilgileri içeren faturaları yüklemeden önce temizle. Dosya başına 5 MB sınırı uygulanır.</div><div class="panel" style="margin-top:16px">${found.length?found.map(({r,a,k})=>`<div class="entry"><div><h4>${esc(a.name)}</h4><p>${esc(r.title||r.station||k)} • ${esc(k)}</p></div><div class="right"><button class="btn tiny" data-file="${esc(a.path)}">Aç</button></div></div>`).join(''):'<div class="empty">Henüz belge eklenmemiş.</div>'}</div>`}
function render(){navUI();$('pageTitle').textContent=NAV.find(x=>x[0]===state.page)?.[2]||'Dashboard';let html='';switch(state.page){case'dashboard':html=dashboard();break;case'tools':html=toolPage();break;case'maintenance':html=listPage('maintenance','Bakım defteri','Servis geçmişi, yapılan işlemler ve periyodik bakım planları.');break;case'issues':html=listPage('issues','Arıza & yapılacaklar','Belirtileri, teşhisleri ve çözümleri aynı kayıtta takip et.');break;case'expenses':html=section('expenses','Masraf defteri','Bakım ve yakıt kayıtlarını yeniden girmene gerek yok; grafiğe otomatik dahil.')+expenseSummary()+`<div class="panel">${records('expenses').length?records('expenses').map(r=>entryCard('expenses',r)).join(''):'<div class="empty">Henüz bağımsız harcama yok.</div>'}</div>`;break;case'fuel':html=listPage('fuel','Yakıt defteri','Dolumları kaydet; tam depo aralıklarıyla tüketim hesapla.');break;case'reminders':html=listPage('reminders','Muayene & sigorta','Önemli son tarihleri takip et. Uyarılar sayfayı açtığında görünür.');break;case'documents':html=docsPage();break}if(!state.connected)html='<div class="warnbox" style="margin-bottom:15px">GitHub bağlantısı yok. Veriler yalnızca son yerel kopyadan gösteriliyor; kayıt ekleme ve değişiklikler bağlantı sağlanana kadar kapalı.</div>'+html;$('content').innerHTML=html;}
function choices(kind,val){return kind.split(':')[1].split(',').map(c=>`<option value="${c}" ${val===c?'selected':''}>${esc(enums.status[c]||enums.severity[c]||enums.type[c]||categoryNames[c]||c)}</option>`).join('')}
function renderFields(k,record){const defs=fieldDefs[k],html=defs.map(([name,label,type,req])=>{let value=record?.[name];if(value===undefined||value===null){value=name==='date'||name==='reportedDate'?today():name==='status'?k==='issues'?'open':'active':name==='severity'?'medium':name==='category'?'other':name==='type'?'inspection':''}if(Array.isArray(value))value=value.join(', ');let input='';if(type==='textarea')input=`<textarea name="${name}" ${req?'required':''}>${esc(value)}</textarea>`;else if(type.startsWith('select:'))input=`<select name="${name}">${choices(type,value)}</select>`;else if(type==='checkbox')input=`<input type="checkbox" name="${name}" ${value?'checked':''}>`;else input=`<input name="${name}" type="${type}" value="${esc(value)}" ${req?'required':''} ${type==='number'?'min="0" step="any"':''}>`;return `<div class="field ${['title','description','symptoms','notes','parts','issueIds'].includes(name)?'full':''}"><label>${esc(label)}${req?' *':''}</label>${input}</div>`}).join('');return html+(k!=='plans'?`<div class="field full"><label>Fotoğraf / fatura ekle (en fazla 5 MB, PDF / JPEG / PNG / WebP)</label><input type="file" name="attachment" accept="application/pdf,image/png,image/jpeg,image/webp"></div>`:'')}
function openModal(k,id){if(!state.connected){toast('Önce GitHub bağlantısı gerekli');return}const r=id?records(k).find(r=>r.id===id):null;state.editing={k,id};$('modalSub').textContent=r?'KAYDI DÜZENLE':'YENİ KAYIT';$('modalTitle').textContent=({maintenance:'Bakım',issues:'Arıza',expenses:'Masraf',fuel:'Yakıt dolumu',reminders:'Hatırlatıcı',plans:'Bakım planı'})[k];$('formFields').innerHTML=renderFields(k,r);$('modal').showModal()}
function closeModal(){$('modal').close();state.editing=null}
async function uploadAttachment(k,id,file){if(!file)return null;if(file.size>5*1024*1024)throw Error('Dosya 5 MB sınırını aşıyor');const exts={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','application/pdf':'pdf'};const ext=exts[file.type];if(!ext)throw Error('Yalnızca PDF/JPEG/PNG/WebP destekleniyor');const path=`uploads/${k}/${id}/${uid('file')}.${ext}`;const bytes=new Uint8Array(await file.arrayBuffer());await writePath(path,bytes,null,`docs: upload MX-3 ${k} attachment`,true);return {id:uid('attachment'),name:file.name,path,mimeType:file.type,size:file.size}}
async function handleSubmit(e){e.preventDefault();const {k,id}=state.editing||{};if(!k)return;const form=$('recordForm');if(!form.reportValidity())return;const fd=new FormData(form);let existing=id?records(k).find(r=>r.id===id):null;let obj=existing?clone(existing):{id:uid(k),attachments:[]};for(const [name,,type]of fieldDefs[k]){const v=type==='checkbox'?fd.has(name):fd.get(name);obj[name]=type==='number'?v===''?null:Number(v):['parts','issueIds'].includes(name)?String(v||'').split(',').map(x=>x.trim()).filter(Boolean):v;}if(k==='fuel'&&(obj.liters<=0||obj.km<0||obj.totalCost<0))return toast('Yakıt miktarı ve kilometreyi kontrol et');if(k==='expenses'&&obj.amount<0)return toast('Tutar negatif olamaz');const file=fd.get('attachment');const submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Kaydediliyor…';try{if(file?.size){const a=await uploadAttachment(k,obj.id,file);obj.attachments=[...(obj.attachments||[]),a]}await saveRecord(k,obj);closeModal();toast('GitHub’a kaydedildi ✓')}catch(err){toast('Kayıt başarısız: '+err.message)}finally{submit.disabled=false;submit.textContent='Kaydet'}}
async function toggleTool(id,value){if(!state.connected){toast('GitHub bağlı değil');return}state.toolChanges.set(id,value);const set=new Set(state.data.tools.checked||[]);value?set.add(id):set.delete(id);state.data.tools={...state.data.tools,checked:[...set]};remember('tools');render();if(!state.toolBusy)flushTools()}
async function flushTools(){if(!state.toolChanges.size||state.toolBusy||!state.connected)return;state.toolBusy=true;setSync('Kaydediliyor…');try{while(state.toolChanges.size){const changes=new Map(state.toolChanges);for(let attempt=0;attempt<4;attempt++){const remote=await readPath('inventory.json');const obj=remote.data||empty('tools');const set=new Set(obj.checked||[]);for(const [id,v]of changes)v?set.add(id):set.delete(id);obj.checked=[...set].sort();obj.updatedAt=new Date().toISOString();try{const sha=await writePath('inventory.json',obj,remote.sha,'chore: update MX-3 garage inventory');state.shas.tools=sha;for(const [id,v]of changes)if(state.toolChanges.get(id)===v)state.toolChanges.delete(id);const visible=new Set(obj.checked);for(const [id,v]of state.toolChanges)v?visible.add(id):visible.delete(id);state.data.tools={...obj,checked:[...visible]};remember('tools');setSync('GitHub’a kaydedildi ✓');break}catch(e){if(!e.conflict||attempt===3)throw e}}}}catch(e){setSync('Kayıt başarısız',true);toast('Takım listesi kaydedilemedi: '+e.message)}finally{state.toolBusy=false;render()}}
async function downloadBackup(){const out={app:'mx3-garage',schemaVersion:2,exportedAt:new Date().toISOString(),data:state.data};const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mx3-garaj-yedek-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('JSON yedeği indirildi (belge dosyalarını içermez)')}
async function openFile(path){try{const r=await fetch(ghUrl(path),{headers:headers(),cache:'no-store'});if(!r.ok)throw Error('Dosya okunamadı');const d=await r.json();const bytes=base64ToBytes(d.content);const name=path.split('/').pop();const mime={pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',webp:'image/webp'}[name.split('.').pop()]||'application/octet-stream';const url=URL.createObjectURL(new Blob([bytes],{type:mime}));window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){toast(e.message)}}
$('nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)nav(b.dataset.page)});
$('mobilebar').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;if(b.dataset.page==='more'){const choice=prompt('Bölüm seç: 5 Masraflar, 6 Yakıt, 7 Tarihler, 8 Belgeler');const n=Number(choice);if(n>=5&&n<=8)nav(NAV[n-1][0])}else nav(b.dataset.page)});
$('content').addEventListener('click',async e=>{const add=e.target.closest('[data-add]');if(add)return openModal(add.dataset.add);const act=e.target.closest('[data-action]');if(act?.dataset.action==='odo'){if(!state.connected)return toast('GitHub bağlı değil');const raw=prompt('Güncel kilometre (km):',state.data.vehicle?.odometer.currentKm??'');if(raw===null)return;const km=Number(raw.replace(',','.'));if(!Number.isFinite(km)||km<0)return toast('Geçerli kilometre gir');try{await saveVehicle(km);toast('Kilometre kaydedildi')}catch(err){toast(err.message)}return}const edit=e.target.closest('[data-edit]');if(edit){const [k,id]=edit.dataset.edit.split(':');return openModal(k,id)}const del=e.target.closest('[data-delete]');if(del){if(!confirm('Bu kaydı silmek istediğine emin misin? (Ekli dosyalar arşivde kalabilir.)'))return;const [k,id]=del.dataset.delete.split(':');try{await delRecord(k,id);toast('Kayıt silindi')}catch(err){toast(err.message)}return}const file=e.target.closest('[data-file]');if(file)return openFile(file.dataset.file)});
$('content').addEventListener('change',e=>{if(e.target.matches('[data-tool]'))toggleTool(e.target.dataset.tool,e.target.checked);if(e.target.matches('#toolFilter')){state.filter=e.target.value;render()}});
$('content').addEventListener('input',e=>{if(e.target.matches('#toolSearch')){const el=e.target,begin=el.selectionStart;state.search=el.value;render();const next=$('toolSearch');next.focus();next.setSelectionRange(begin,begin)}});
$('content').addEventListener('toggle',e=>{if(e.target.matches('details[data-group]'))state.toolOpen.set(Number(e.target.dataset.group),e.target.open)},true);
$('recordForm').addEventListener('submit',handleSubmit);$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('syncNow').onclick=async()=>{if(state.busy.size||state.toolBusy||state.toolChanges.size)return toast('Bekleyen kayıt var');await connect();toast(state.connected?'GitHub verileri yenilendi':'Bağlantı kurulamadı')};$('downloadBackup').onclick=downloadBackup;
for(const k of Object.keys(PATHS))state.data[k]=readLocal(k)||empty(k);render();connect();
