const OWNED = ['Gunpla 1/4" 2–24 Nm tork anahtarı','Gunpla 1/4" Hex / Torx / Phillips uçlar','Gunpla 100 mm uzatma','Gunpla 1/4" mafsal','Gunpla 1/4" → 3/8" adaptör','Multimetre'];
const DATA = [
{title:'Temel el aletleri',subtitle:'Stoplar, IAC, hava emiş sistemi, gündelik işler',items:[
['ratchet38','3/8" cırcır kolu','Motor bölmesi için ana cırcır'],['sockets38','3/8" 8–19 mm 6 köşe lokma seti','Özellikle 8, 10, 12, 14, 17 ve 19 mm'],['deepsockets','3/8" uzun lokmalar','Ulaşılması güç somunlar'],['extensions38','3/8" uzatma çubukları','75 ve 150 mm civarı'],['universal38','3/8" mafsallı adaptör','Açılı bağlantılar'],['wrenches','8–19 mm kombine anahtar seti','Açık ağız + yıldız'],['screwdrivers','Düz ve Phillips tornavidalar','PH1/PH2 dâhil'],['pliers','Pense','Genel kullanım'],['longnose','Kargaburun','Dar alanlar'],['cutters','Yan keski','Kablo/kelepçe'],['lamp','Şarjlı çalışma feneri','Mıknatıslı veya kafa lambası'],['trim','Plastik trim sökme aparatı','Döşeme klipsleri'],['magnet','Teleskopik mıknatıs','Düşen vida ve somunlar']]},
{title:'Takımı genişletme',subtitle:'Bujiler, küçük ve büyük bağlantılar',items:[
['ratchet14','1/4" mini cırcır','Tork anahtarını sökme amaçlı yormamak için'],['sockets14','1/4" 4–13 mm altıgen lokmalar','Gunpla uçlarını tamamlar'],['ratchet12','1/2" cırcır','Büyük bağlantılar'],['sockets12','1/2" 17–24 mm lokmalar','Büyük somun/cıvatalar'],['breaker','1/2" kırma kol','Sıkı bağlantıları gevşetme'],['sparkplug','16 mm buji lokması','Satın almadan önce mevcut buji/erişimi kontrol et'],['torquehigh','Yüksek aralıklı tork anahtarı','Örn. 40–200 Nm; seçimi işin torkuna göre yap'],['adapters','Lokma adaptörleri','Eksik ölçü geçişleri; Gunpla 1/4→3/8 sende var'],['hosepliers','Hortum kelepçe pensesi','Hortum sökme'],['mallet','Kauçuk tokmak','Hassas parçalar'],['feeler','Sentil çakısı','Buji aralığı ve boşluk ölçümleri']]},
{title:'Elektrik ve arıza tespiti',subtitle:'Park lambaları, soketler, kablo işleri, sunroof',items:[
['probes','İnce multimetre probları','Soketlere zarar vermeden ölçüm'],['testlamp','12 V otomotiv test lambası','Yalnızca uygun devrelerde kullan'],['fuse','Sigorta çekme aparatı','Sigorta değişimi'],['contact','Elektrik kontak temizleyici','Soket bağlantıları'],['crimper','Kablo soyma ve krimp pensesi','Kablo onarımı'],['heatshrink','Isıyla daralan makaron seti','Yalıtım'],['heatgun','Isı tabancası','Makaron için'],['alligator','Krokodil uçlu test kabloları','Ölçüm bağlantıları'],['zipties','UV dayanımlı kablo bağı','Kablo/tesisat sabitleme'],['drain','Esnek plastik tahliye temizleme teli','Sunroof giderleri; sert metal tel kullanma']]},
{title:'Araç altı ve periyodik bakım',subtitle:'Yağ, tekerlek, fren, alt takım; güvenli zemin gerektirir',items:[
['jack','Düşük profilli hidrolik kriko','Aracın yüksekliğine uygun'],['stands','Kriko sehpaları (en az 2)','Araç altında çalışırken zorunlu'],['chocks','Teker takozları','Kaymayı engeller'],['jackpad','Uygun kriko pedi','Kaldırma noktasına uygun'],['wheelnut','Bijon lokması','Üzerindeki bijon ölçüsünü kontrol et'],['filtertool','Yağ filtresi sökme anahtarı','Yağ değişimi'],['drainpan','Yağ toplama kabı','Atık yağ için'],['funnel','Huni','Sıvı dolumu'],['bleeder','Fren hava alma kiti','Fren hidroliği işleri'],['flare','Fren rakor anahtarı','Fren borusu bağlantıları'],['wirebrush','Tel fırça','Pas temizliği'],['penetrant','Pas sökücü sprey','Sıkışmış bağlantılar']]},
{title:'İleri seviye / işe özel',subtitle:'Motor, şanzıman ve süspansiyon; yalnızca gerektiğinde al',items:[
['compression','Kompresyon test cihazı','Motor sağlığı'],['coolant','Soğutma sistemi basınç test kiti','Kaçak tespiti'],['vacuum','Vakum pompası ve manometre','Vakum teşhisi'],['fuel','Yakıt basınç test kiti','Yakıt sistemi teşhisi'],['pulleyhold','Krank kasnağı tutma aparatı','Kasnak işleri'],['puller','Kasnak çektirmesi','Kasnak sökme'],['balljoint','Rotil ayırma aparatı','Ön takım'],['bearing','Rulman çekme/basma ekipmanı','Rulman işleri'],['enginebar','Motor destek traversi','Motor/şanzıman desteği'],['clutch','Debriyaj merkezleme aparatı','Debriyaj işi'],['spring','Yay sıkıştırma aparatı','Yüksek risk; tercihen profesyonel ekipman/uygulama']]}
];
